alter session set current_schema = "as2";
ALTER USER "as2" quota unlimited on "USERS";


CREATE TABLE CLEANER (
    staff_workshop_workshop_id  NUMBER NOT NULL,
    overtime_rate               NUMBER NOT NULL,
    employee_of_the_month_bonus NUMBER NOT NULL
);

CREATE TABLE craftman (
    staff_workshop_workshop_id NUMBER NOT NULL,
    ongoing_product            VARCHAR2(50)
);

CREATE TABLE customer (
    workshop_workshop_id                     NUMBER NOT NULL,
    customer_id                              INTEGER NOT NULL,
    customer_name                            NVARCHAR2(100) NOT NULL,
    phone_number                             INTEGER NOT NULL,
    Email                                    NVARCHAR2(150) NOT NULL,
    payment                                  NUMBER NOT NULL,
    DiscountPromotion                        NUMBER NOT NULL
);

CREATE TABLE customer_address_id (
    workshop_workshop_id  NUMBER NOT NULL,
    customer_address_id   INTEGER NOT NULL,
    district              NVARCHAR2(50) NOT NULL,
    city                  NVARCHAR2(50) NOT NULL,
    street                NVARCHAR2(50) NOT NULL,
    house_number          INTEGER NOT NULL,
    zip_code              NVARCHAR2(50) NOT NULL,
    customer_customer_id  INTEGER NOT NULL
);

CREATE TABLE facilitator (
    staff_workshop_workshop_id NUMBER NOT NULL,
    FACdegree                  NVARCHAR2(100) NOT NULL,
    skill_level                NVARCHAR2(100) NOT NULL
);

CREATE TABLE first_aider (
    staff_workshop_workshop_id NUMBER NOT NULL,
    license                    NVARCHAR2(100) NOT NULL,
    training                   NVARCHAR2(1) NOT NULL,
    experience                 NVARCHAR2(150) NOT NULL
);

CREATE TABLE mainsmanager (
    staff_workshop_workshop_id NUMBER NOT NULL,
    budget                     NUMBER NOT NULL,
    target_revenue             NUMBER NOT NULL,
    semyear                    INTEGER NOT NULL
);

CREATE TABLE "Order" (
    workshop_workshop_id NUMBER NOT NULL,
    order_id             INTEGER NOT NULL,
    quantity             INTEGER NOT NULL,
    total_cost           NUMBER NOT NULL,
    staff_staff_id       INTEGER NOT NULL,
    product_product_id   INTEGER,
    order_cost_order_id  INTEGER NOT NULL
);

CREATE TABLE order_cost (
    workshop_workshop_id NUMBER NOT NULL,
    order_id             INTEGER NOT NULL,
    quantity             INTEGER NOT NULL,
    total_cost           NUMBER NOT NULL,
    order_order_id       INTEGER NOT NULL
);

CREATE TABLE part (
    workshop_workshop_id NUMBER NOT NULL,
    part_id              INTEGER NOT NULL,
    part_name            NVARCHAR2(100) NOT NULL,
    stock                INTEGER NOT NULL,
    part_supplier        NVARCHAR2(100) NOT NULL
);

CREATE TABLE product (
    workshop_workshop_id NUMBER NOT NULL,
    product_id           INTEGER NOT NULL,
    product_name         NVARCHAR2(100) NOT NULL,
    product_description  VARCHAR2(4000) NOT NULL,
    product_category     NVARCHAR2(50) NOT NULL,
    price_per_unit       NUMBER NOT NULL,
    part_part_id         INTEGER,
    order_order_id       INTEGER NOT NULL
);



CREATE TABLE repair_technician (
    staff_workshop_workshop_id NUMBER NOT NULL,
    last_inspection            DATE NOT NULL,
    next_inspection            DATE NOT NULL
);

CREATE TABLE "Session" (
    workshop_workshop_id NUMBER NOT NULL,
    session_id           INTEGER NOT NULL,
    session_time         DATE NOT NULL,
    Workspace_no         INTEGER NOT NULL,
    session_cost         NUMBER NOT NULL
);

CREATE TABLE staff (
    workshop_workshop_id            NUMBER NOT NULL,
    staff_id                        INTEGER NOT NULL,
    staff_name                      NVARCHAR2(100) NOT NULL,
    phone_number                    INTEGER NOT NULL,
    Email                           NVARCHAR2(150) NOT NULL,
    salary                          NUMBER NOT NULL
);

CREATE TABLE staff_address (
    workshop_workshop_id NUMBER NOT NULL,
    staff_address_id     INTEGER NOT NULL,
    district             NVARCHAR2(50) NOT NULL,
    city                 NVARCHAR2(50) NOT NULL,
    street               NVARCHAR2(50) NOT NULL,
    house_number         INTEGER NOT NULL,
    zip_code             NVARCHAR2(50) NOT NULL
);

CREATE TABLE supervisor (
    staff_workshop_workshop_id NUMBER NOT NULL,
    assigned_room              INTEGER NOT NULL
);

CREATE TABLE tool (
    workshop_workshop_id NUMBER NOT NULL,
    tool_id              INTEGER NOT NULL,
    tool_name            NVARCHAR2(1) NOT NULL,
    available            INTEGER NOT NULL,
    supplier             NVARCHAR2(100) NOT NULL,
    tool_type            NVARCHAR2(50) NOT NULL
);

CREATE TABLE workshop (
    workshop_id NUMBER NOT NULL
);

DESCRIBE CLEANER

DESCRIBE CRAFTMAN

DESCRIBE CUSTOMER

DESCRIBE CUSTOMER_ADDRESS_ID

DESCRIBE FACILITATOR

DESCRIBE FIRST_AIDER

DESCRIBE MAINSMANAGER

DESCRIBE "Order"

DESCRIBE ORDER_COST

DESCRIBE PART

DESCRIBE PRODUCT

DESCRIBE REPAIR_TECHNICIAN

DESCRIBE "Session"

DESCRIBE STAFF

DESCRIBE STAFF_ADDRESS

DESCRIBE SUPERVISOR

DESCRIBE TOOL

DESCRIBE WORKSHOP

ALTER TABLE CLEANER
    RENAME COLUMN STAFF_WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE CLEANER
    MODIFY(OVERTIME_RATE DECIMAL(3,2));
ALTER TABLE CLEANER
    Add(STAFF_ID INT NOT NULL);
    DESCRIBE CLEANER
    
ALTER TABLE CRAFTMAN
    RENAME COLUMN STAFF_WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE CRAFTMAN
    ADD(STAFF_ID INT NOT NULL);
    DESCRIBE CRAFTMAN
    
ALTER TABLE CUSTOMER
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE CUSTOMER
    MODIFY(PAYMENT VARCHAR2(20),
    DISCOUNTPROMOTION NVARCHAR2(3));
    DESCRIBE CUSTOMER

    
ALTER TABLE CUSTOMER_ADDRESS_ID
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE CUSTOMER_ADDRESS_ID 
    RENAME COLUMN CUSTOMER_CUSTOMER_ID TO CUSTOMER_ID;
    DESCRIBE CUSTOMER_ADDRESS_ID
    
ALTER TABLE FACILITATOR
    RENAME COLUMN STAFF_WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE FACILITATOR
    RENAME COLUMN FACDEGREE TO "DEGREE";
ALTER TABLE FACILITATOR
    MODIFY("DEGREE" NVARCHAR2(50),SKILL_LEVEL VARCHAR2(20));
ALTER TABLE FACILITATOR
    ADD(STAFF_ID INT NOT NULL);
DESC FACILITATOR
    
ALTER TABLE FIRST_AIDER
    RENAME COLUMN STAFF_WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE FIRST_AIDER
    MODIFY(TRAINING VARCHAR2(20),LICENSE VARCHAR2(10),
    EXPERIENCE NVARCHAR2(20));
ALTER TABLE FIRST_AIDER
    ADD(STAFF_ID INT NOT NULL);
    DESC first_aider
    
ALTER TABLE MAINSMANAGER
    RENAME COLUMN STAFF_WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE MAINSMANAGER
    RENAME TO "MANAGER";
ALTER TABLE "MANAGER"
    RENAME COLUMN SEMYEAR TO "YEAR";
ALTER TABLE "MANAGER"
    MODIFY("YEAR" NVARCHAR2(10));
DESCRIBE MANAGER;
    
ALTER TABLE "Order"
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE "Order"
    RENAME COLUMN STAFF_STAFF_ID TO STAFF_ID;
ALTER TABLE "Order"
    RENAME COLUMN PRODUCT_PRODUCT_ID TO PRODUCT_ID;
ALTER TABLE "Order"
    RENAME COLUMN ORDER_COST_ORDER_ID TO ORDER_COST;
    DESC "Order"
    
ALTER TABLE ORDER_COST
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE ORDER_COST
    RENAME COLUMN ORDER_ORDER_ID TO ORDER_ID;
ALTER TABLE ORDER_COST
    DROP COLUMN ORDER_ORDER_ID;
    DESC ORDER_COST
    
ALTER TABLE PART
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
    DESC PART
    
ALTER TABLE PRODUCT
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE PRODUCT
    RENAME COLUMN PART_PART_ID TO PART_ID;
ALTER TABLE PRODUCT
    RENAME COLUMN ORDER_ORDER_ID TO ORDER_ID;
    DESC PRODUCT
    
ALTER TABLE REPAIR_TECHNICIAN
    RENAME COLUMN STAFF_WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE REPAIR_TECHNICIAN
    ADD TOOL_NAME VARCHAR2(30);
ALTER TABLE REPAIR_TECHNICIAN
    ADD STAFF_ID NUMBER;
    DESC REPAIR_TECHNICIAN

ALTER TABLE "Session"
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
    DESC "Session"

ALTER TABLE STAFF
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE STAFF
    MODIFY(PHONE_NUMBER NUMBER(7));
    DESC STAFF
    
ALTER TABLE STAFF_ADDRESS
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
    DESC STAFF_ADDRESS
    
ALTER TABLE SUPERVISOR
    RENAME COLUMN STAFF_WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE SUPERVISOR
    ADD STAFF_ID NUMBER;
    DESC SUPERVISOR
    
ALTER TABLE TOOL
    RENAME COLUMN WORKSHOP_WORKSHOP_ID TO WORKSHOP_ID;
ALTER TABLE TOOL
    MODIFY TOOL_NAME VARCHAR2(30);
    DESC TOOL



DROP TABLE CLEANER;

DROP TABLE CRAFTMAN;

DROP TABLE CUSTOMER;

DROP TABLE CUSTOMER_ADDRESS_ID;

DROP TABLE FACILITATOR;

DROP TABLE FIRST_AIDER;

DROP TABLE MAINSMANAGER;

DROP TABLE "Order";

DROP TABLE ORDER_COST;

DROP TABLE PART;

DROP TABLE PRODUCT;

DROP TABLE REPAIR_TECHNICIAN;

DROP TABLE "Session";

DROP TABLE STAFF;

DROP TABLE STAFF_ADDRESS;

DROP TABLE SUPERVISOR;

DROP TABLE TOOL;

DROP TABLE WORKSHOP;


--and this

TRUNCATE TABLE CLEANER;
SELECT * FROM CLEANER;

TRUNCATE TABLE CRAFTMAN;
SELECT * FROM CRAFTMAN;

TRUNCATE TABLE CUSTOMER;
SELECT * FROM CUSTOMER;

TRUNCATE TABLE CUSTOMER_ADDRESS_ID;
SELECT * FROM CUSTOMER_ADDRESS_ID;

TRUNCATE TABLE FACILITATOR;
SELECT * FROM FACILITATOR;

TRUNCATE TABLE FIRST_AIDER;
SELECT * FROM FIRST_AIDER;

TRUNCATE TABLE MANAGER;
SELECT * FROM MANAGER;

TRUNCATE TABLE "Order";
SELECT * FROM "Order";

TRUNCATE TABLE ORDER_COST;
SELECT * FROM ORDER_COST;

TRUNCATE TABLE PART;
SELECT * FROM PART;

TRUNCATE TABLE PRODUCT;
SELECT * FROM PRODUCT;

TRUNCATE TABLE REPAIR_TECHNICIAN;
SELECT * FROM REPAIR_TECHNICIAN;

TRUNCATE TABLE "Session";
SELECT * FROM "Session";

TRUNCATE TABLE STAFF;
SELECT * FROM STAFF;

TRUNCATE TABLE STAFF_ADDRESS;
SELECT * FROM STAFF_ADDRESS;

TRUNCATE TABLE SUPERVISOR;
SELECT * FROM SUPERVISOR;

TRUNCATE TABLE TOOL;
SELECT * FROM TOOL;

TRUNCATE TABLE WORKSHOP;
SELECT * FROM WORKSHOP;


--and this

ALTER TABLE CLEANER
DROP COLUMN column_name;

ALTER TABLE CRAFTMAN
DROP COLUMN column_name;

ALTER TABLE CUSTOMER
DROP COLUMN column_name;

ALTER TABLE CUSTOMER_ADDRESS_ID
DROP COLUMN column_name;

ALTER TABLE FACILITATOR
DROP COLUMN column_name;

ALTER TABLE FIRST_AIDER
DROP COLUMN column_name;

ALTER TABLE MAINSMANAGER
DROP COLUMN column_name;

ALTER TABLE "Order"
DROP COLUMN column_name;

ALTER TABLE ORDER_COST
DROP COLUMN column_name;

ALTER TABLE PART
DROP COLUMN column_name;

ALTER TABLE PRODUCT
DROP COLUMN column_name;

ALTER TABLE REPAIR_TECHNICIAN
DROP COLUMN column_name;

ALTER TABLE "Session"
DROP COLUMN column_name;

ALTER TABLE STAFF
DROP COLUMN column_name;

ALTER TABLE STAFF_ADDRESS
DROP COLUMN column_name;

ALTER TABLE SUPERVISOR
DROP COLUMN column_name;

ALTER TABLE TOOL
DROP COLUMN column_name;

ALTER TABLE WORKSHOP
DROP COLUMN column_name;


INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00001,1,58);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00002,1,48);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00003,3,102);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00004,1,30);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00005,3,150);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00006,1,35);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00007,2,70);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00008,2,74);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00009,4,190);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST)
VALUES(001,00010,1,25);

select * from order_cost;

INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,220,'SOLIDWOOD',200,'KAYUBN');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,230,'VERNEERWOOD',420,'KAYUBN');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,250,'MDFWOOD',560,'KAYUBN');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,300,'STEEL SHEETS',250,'LIM MACHINERY SDN BHD');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,310,'ALUMINUM SHEETS',170,'LIM MACHINERY SDN BHD');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,520,'MOULDED PLASTICS TYPE 1',120,'ABU BAKAR SDN BHD');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,550,'MOULDED PLASTICS TYPE 2',127,'ABU BAKAR SDN BHD');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,560,'MOULDED PLASTICS TYPE 3',131,'ABU BAKAR SDN BHD');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,570,'PINEWOOD',58,'ABU BAKAR SDN BHD');
INSERT INTO PART (WORKSHOP_ID, PART_ID, PART_NAME, STOCK, PART_SUPPLIER)
VALUES(001,590,'LAMINATE',700,'ABU BAKAR SDN BHD');

SELECT * FROM PART;

INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,101,'WOODEN ROCKING CHAIR','A TYPE OF CHAIR WITH TWO CURVED BANDS ATTACHED TO THE BOTTOM OF THE LEGS MADE OF SOLID WOOD AND VERNEER WOOD.','FURNITURE',320,220,00001);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,111,'WOODEN VASE','A VASE MADE FROM MDF AND PINEWOOD WITH A VERY UNIQUE DESIGN AESTHETIC. DIMENSIONS: 0.5M X 0.5M X 1.3M (L X B X H)','DECORATIONS',30,250,00002);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,121,'WOODEN BOX','A COMPACT BOX USED TO STORE ITEMS. DIMENSIONS OF 1M X 1M X 1M. MADE FROM VERNEER AND MDF WOOD','STORAGE',15,230,00003);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,131,'CUP COASTER','A COASTER THAT HELP TO KEEP THE CONDENSATION FROM LEAVING WATER MARKS BEHIND','KITCHEN',5,250,00004);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,132,'PLATE HOLDER','A PLATE HOLDER MADE UP OF PLASTIC 
AND IS USED TO HOLD PLATES OR DISHES. THIS PRODUCT COULD ALSO HOLD OTHER ITEMS SUCH AS CUTLERY AND TOWELS','KITCHEN',10,520,00005);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,133,'SPOON AND FORKS','A SPECIALY DESIGNED SPOON AND 
FORK MADE FROM ALUMINUM AND PLASTIC. USED FOR CASUAL MEALS AND DESSERTS. THIS ITEM HAS A UNIQUE DESIGN AESTHETIC THAT REPRESENTS A 
FLORAL DESIGN. THIS SET CONTAINS 10 SPOON AND FORKS','KITCHEN',15,310,00006);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,102,'TALL BOOKSHELF','A SHELF TO STORE BOOKS. THIS ITEM HAS DIMENSIONS OF 3M X 2M X 2M. MADE FROM MDF AND LAMINATE','FURNITURE',90,250,00007);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,134,'METAL CHOPING KNIFE','A KNIFE BEST USED FOR CHOPING MEATS AND HARD FOODS LIKE COCONUTS! THIS ITEM IS MADE OUT OF STEEL AND ALUMINUM.','KITCHEN',8.90,300,00008);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,103,'DINING TABLE','LONG AND PREMIUM DINING TABLE MADE FROM SOLID WOOD. THIS TABLE IS PROFESSIONALLY MANUFACTURED AND IS QUALITY CHECKED BY EXPERTS.','FURNITURE',2250,200,00009);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,112,'HEADPHONE HOLDER','A CUSTOM MADE HEADPHONE STAND/HOLDER TO STORE OVER EAR HEADPHONES.','DECORATIONS',18,250,00010);

SELECT * FROM PRODUCT;


INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,311010,TO_DATE('10-31-2021','MM-DD-YYYY'),0010,50);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,311020,TO_DATE('10-31-2021','MM-DD-YYYY'),0020,70);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,311021,TO_DATE('10-31-2021','MM-DD-YYYY'),0021,70);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,141111,TO_DATE('11-14-2021','MM-DD-YYYY'),0011,50);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,141120,TO_DATE('11-14-2021','MM-DD-YYYY'),0020,70);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,171120,TO_DATE('11-17-2021','MM-DD-YYYY'),0020,75);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,281010,TO_DATE('10-28-2021','MM-DD-YYYY'),0010,50);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,291020,TO_DATE('10-29-2021','MM-DD-YYYY'),0020,75);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,301010,TO_DATE('10-30-2021','MM-DD-YYYY'),0010,50);
INSERT INTO "Session" (WORKSHOP_ID, SESSION_ID, SESSION_TIME, WORKSPACE_NO, SESSION_COST)
VALUES(001,031222,TO_DATE('12-03-2021','MM-DD-YYYY'),0022,70);

SELECT * FROM "Session";


INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,0723,'Sam Mendes',1456232,'Sam@gmail.com',250);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,0853,'Tony Stark',9993345,'Tony@gmail.com',300);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,0865,'Leornardo Da’vincci',7878096,'Leo@gmail.com',150);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,0975,'Viktor Frank',9019502,'Viktor@gmail.com',140);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,1085,'Jokko Widodo',3401921,'Jokko@gmail.com',200);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,1235,'John Williams',2777414,'John@gmail.com',230);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,2874,'Willy Wonka',7000102,'Willy@gmail.com',220);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,3451,'Annie Kate',5604018,'Annie@gmail.com',310);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,6291,'Park Chan Wook',3434767,'Park@gmail.com',340);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,6788,'Raja Lear',7647828,'Raja@gmail.com',350);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,8392,'Ryan Gosling',5012345,'Ryan@gmail.com',230);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,0363,'Ben Affleck',1010999,'Ben@gmail.com',200);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,4528,'Peter Jackson',2183450,'Peter@gmail.com',245);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,9362,'Urdu Murdu',4560321,'Urdu@gmail.com',400);
INSERT INTO STAFF (WORKSHOP_ID, STAFF_ID, STAFF_NAME, PHONE_NUMBER, EMAIL, SALARY)
VALUES(001,5282,'Ooga Booga',4680421,'OG@gmail.com',100);

select * from staff;

INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,0723,'BSB','MERAGANG','SIMPANG 55',10,'BE3319');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,0853,'BSB','MERAGANG','SIMPANG 89',22,'BE3319');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,0723,'BSB','MERAGANG','SIMPANG 35',4,'BE3319');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,0853,'BSB','LAMBAK KANAN','SIMPANG 87',6,'BU1230');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,0865,'BSB','SERASA','SIMPANG 64',62,'BS4770');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,0975,'BSB','LAMBAK KANAN','SIMPANG 23',92,'BU1230');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,1085,'BSB','LAMBAK KIRI','SIMPANG 102',22,'BB1214');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,1235,'TTG','KIUDANG','SIMPANG 155',30,'TE1543');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,2874,'TTG','TELISAI','SIMPANG 5',10,'TT1503');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,3451,'TTG','TANJONG MAYA','SIMPANG 72',9,'TM8809');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,6291,'TTG','TANJONG MAYA','SIMPANG 32',85,'TM8809');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,6788,'BSB','JERUDONG','SIMPANG 493',88,'BG3122');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,8392,'BSB','MERAGANG','SIMPANG 438',42,'BE3319');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,0363,'TTG','TELISAI','SIMPANG 88',27,'TT1503');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,4528,'TTG','KIUDANG','SIMPANG 210',7,'TE1543');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,9362,'BSB','SERASA','SIMPANG 54',50,'BS4770');
INSERT INTO STAFF_ADDRESS (WORKSHOP_ID, STAFF_ADDRESS_ID, DISTRICT, CITY, STREET, HOUSE_NUMBER, ZIP_CODE)
VALUES(001,5282,'BSB','LAMBAK KIRI','SIMPANG 93',110,'BB1214');

SELECT * FROM STAFF_ADDRESS;

INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0010,0733);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0011,1923);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0012,0911);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0020,0455);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0021,1916);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0022,7650);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0030,2323);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0031,9494);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0032,5130);
INSERT INTO SUPERVISOR (WORKSHOP_ID, ASSIGNED_ROOM, STAFF_ID)
VALUES(001,0033,0282);

SELECT * FROM SUPERVISOR;

INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,330,'JIGSAW','30','THE TOOL BOX','SAW');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,331,'CIRCULAR SAW','15','THE TOOL BOX','SAW');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,332,'MITRE SAW','30','THE TOOL BOX','SAW');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,005,'TABLE SAW','10','THE TOOL BOX','MACHINERY');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,006,'TABLE DRILL','15','THE TOOL BOX','MACHINERY');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,333,'HAND SAW','40','THE TOOL BOX','SAW');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,103,'PHILLIPS SCREWDRIVER','70','MR DIY','SCREWDRIVER');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,104,'FLATHEAD SCREWDRIVER','70','MY DIY','SCREWDRIVER');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,105,'ALLEN KEY','130','MY DIY','SCREWDRIVER');
INSERT INTO TOOL (WORKSHOP_ID, TOOL_ID, TOOL_NAME, AVAILABLE, SUPPLIER, TOOL_TYPE)
VALUES(001,201,'JACK HAMMER','4','THE TOOL BOX','MACHINERY');

SELECT * FROM TOOL;

INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(0788,001,0.05,0);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(0821,001,0.05,0);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(0887,001,0.05,0);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(0924,001,0.10,550);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(1024,001,0.05,0);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(1223,001,0.10,500);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(2885,001,0.05,0);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(2936,001,0.10,500);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(3002,001,0.10,500);
INSERT INTO CLEANER(STAFF_ID,WORKSHOP_ID,OVERTIME_RATE,EMPLOYEE_OF_THE_MONTH_BONUS) VALUES(3056,001,0.05,0);
SELECT * FROM CLEANER;


INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(3412,001,54331);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(3412,001,89976);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(9362,001,90144);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(3412,001,63445);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(8216,001,10815);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(8452,001,63773);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(3714,001,23441);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(9562,001,09774);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(8856,001,53553);
INSERT INTO CRAFTMAN(STAFF_ID,WORKSHOP_ID,ONGOING_PRODUCT) VALUES(8452,001,72003);
SELECT * FROM CRAFTMAN;

DESC CUSTOMER;
INSERT INTO CUSTOMER VALUES(001,00010,'MIKE',8345625,'MIKE88@GMAIL.COM','CARD','NA');	
INSERT INTO CUSTOMER VALUES(001,00011,'JAMES',8654334,'JAMESB@YAHOO.COM','CARD','NA');	
INSERT INTO CUSTOMER VALUES(001,00012,'RICHARD',7127635,'RICHARDLIM@YAHOO.COM','CARD','NA');
INSERT INTO CUSTOMER VALUES(001,00013,'JEREMY',7424526,'JEREMYJ@HOTMAIL.COM','CASH',0.2);
INSERT INTO CUSTOMER VALUES(001,00014,'HAMMOND',8805441,'RHAMMOND@GMAIL.COM','CASH',0.3);
INSERT INTO CUSTOMER VALUES(001,00015,'ROSS',8997653,'MIKEROSS@GMAIL.COM','CARD','NA');
INSERT INTO CUSTOMER VALUES(001,00016,'CLARKSON',7662933,'CLARSON66@GMAIL.COM','BANK TRANSFER',0.1);
INSERT INTO CUSTOMER VALUES(001,00017,'WILLY',7768224,'WILLYTHEWILL@GMAIL.COM','CARD','NA');
INSERT INTO CUSTOMER VALUES(001,00018,'SASHA',8016822,'SASHASLOAN@YAHOO.COM','CARD','NA');	
INSERT INTO CUSTOMER VALUES(001,00019,'CLAIRE',7277227,'CLARA.CLAIRE@GMAIL.COM','CASH',0.2);
SELECT * FROM CUSTOMER;


DESC CUSTOMER_ADDRESS_ID;
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1001,001,00010,'BSB','MERAGANG','SIMPANG 10',10,'BE3319');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1002,001,00011,'BSB','JERUDONG','SIMPANG 40',53,'BG3122');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1003,001,00012,'KB','MUMONG','SIMPANG 12',72,'KH5366');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1004,001,00013,'BSB','LAMBAK KANAN','SIMPANG 20',90,'BU1230');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1005,001,00014,'TTG','TELISAI','SIMPANG 34',110,'TT1503');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1006,001,00015,'KB','SERIA','SIMPANG 27',43,'KY5234');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1007,001,00016,'TEMB','LABU','SIMPANG 19',85,'PT2432');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1008,001,00017,'BSB','SERASA','SIMPANG 15',13,'BS4770');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1009,001,00018,'BSB','MENTIRI','SIMPANG 2','22','BA1234');
INSERT INTO CUSTOMER_ADDRESS_ID(CUSTOMER_ADDRESS_ID,WORKSHOP_ID,CUSTOMER_ID,DISTRICT,CITY,
STREET,HOUSE_NUMBER,ZIP_CODE) VALUES(1010,001,00019,'TTG','TANJONG MAYA','SIMPANG 9',63,'TM8809');
SELECT * FROM CUSTOMER_ADDRESS_ID;


DESC Facilitator;

INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,0723,'HND','Expert');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,0853,'DIPLOMA','Proficient');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,0865,'DIPLOMA','Proficient');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,0975,'HND','Expert');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,1085,'HND','Expert');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,1235,'DIPLOMA','Proficient');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,2874,'ALEVEL','Trainee');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,3451,'HND','Expert');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,6291,'ALEVEL','Novice');
INSERT INTO FACILITATOR(WORKSHOP_ID,STAFF_ID,"DEGREE",SKILL_LEVEL) VALUES(001,6788,'DIPLOMA','Proficient');
SELECT * FROM FACILITATOR;


DESC FIRST_AIDER;

INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9980,'VALID','COMPLETED','3 months');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9981,'VALID','COMPLETED','1 years');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9982,'VALID','COMPLETED','5 months');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9983,'EXPIRED','IN PROGRESS','1 years');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9984,'VALID','COMPLETED','1 years');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9985,'VALID','COMPLETED','2 years');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9986,'VALID','COMPLETED','2 years');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9987, 'EXPIRED','PENDING','10 months');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9988,'EXPIRED','IN PROGRESS','1 month');
INSERT INTO FIRST_AIDER(WORKSHOP_ID,STAFF_ID,LICENSE,TRAINING,
EXPERIENCE) VALUES(001,9989,'VALID','COMPLETED','3 years');
SELECT * FROM FIRST_AIDER;

INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00001,1,58,00001);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00002,1,48,00002);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00003,3,102,00003);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00004,1,30,00004);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00005,3,150,00005);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00006,1,35,00006);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00007,2,70,00007);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00008,2,74,00008);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00009,4,190,00009);
INSERT INTO ORDER_COST (WORKSHOP_ID, ORDER_ID, QUANTITY, TOTAL_COST, ORDER_ORDER_ID)
VALUES(001,00010,1,25,00010);
SELECT * FROM ORDER_COST;


INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,101,'WOODEN ROCKING CHAIR','A TYPE OF CHAIR WITH TWO CURVED BANDS ATTACHED TO THE BOTTOM OF THE LEGS MADE OF SOLID WOOD AND VERNEER WOOD.','FURNITURE',320,220,00001);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,111,'WOODEN VASE','A VASE MADE FROM MDF AND PINEWOOD WITH A VERY UNIQUE DESIGN AESTHETIC. DIMENSIONS: 0.5M X 0.5M X 1.3M (L X B X H)','DECORATIONS',30,250,00002);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,121,'WOODEN BOX','A COMPACT BOX USED TO STORE ITEMS. DIMENSIONS OF 1M X 1M X 1M. MADE FROM VERNEER AND MDF WOOD','STORAGE',15,230,00003);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,131,'CUP COASTER','A COASTER THAT HELP TO KEEP THE CONDENSATION FROM LEAVING WATER MARKS BEHIND','KITCHEN',5,250,00004);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,132,'PLATE HOLDER','A PLATE HOLDER MADE UP OF PLASTIC AND IS USED TO HOLD PLATES OR DISHES. THIS PRODUCT COULD ALSO HOLD OTHER ITEMS SUCH AS CUTLERY AND TOWELS','KITCHEN',10,520,00005);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,133,'SPOON AND FORKS','A SPECIALY DESIGNED SPOON AND FORK MADE FROM ALUMINUM AND PLASTIC. USED FOR CASUAL MEALS AND DESSERTS. THIS ITEM HAS A UNIQUE DESIGN AESTHETIC THAT REPRESENTS A FLORAL DESIGN. THIS SET CONTAINS 10 SPOON AND FORKS','KITCHEN',15,310,00006);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,102,'TALL BOOKSHELF','A SHELF TO STORE BOOKS. THIS ITEM HAS DIMENSIONS OF 3M X 2M X 2M. MADE FROM MDF AND LAMINATE','FURNITURE',90,250,00007);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,134,'METAL CHOPING KNIFE','A KNIFE BEST USED FOR CHOPING MEATS AND HARD FOODS LIKE COCONUTS! THIS ITEM IS MADE OUT OF STEEL AND ALUMINUM.','KITCHEN',8.90,300,00008);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,103,'DINING TABLE','LONG AND PREMIUM DINING TABLE MADE FROM SOLID WOOD. THIS TABLE IS PROFESSIONALLY MANUFACTURED AND IS QUALITY CHECKED BY EXPERTS.','FURNITURE',2250,200,00009);
INSERT INTO PRODUCT (WORKSHOP_ID, PRODUCT_ID, PRODUCT_NAME, PRODUCT_DESCRIPTION, PRODUCT_CATEGORY, PRICE_PER_UNIT, PART_ID, ORDER_ID)
VALUES(001,112,'HEADPHONE HOLDER','A CUSTOM MADE HEADPHONE STAND/HOLDER TO STORE OVER EAR HEADPHONES.','DECORATIONS',18,250,00010);

SELECT * FROM PRODUCT;


INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('06-02-2021','MM-DD-YYYY'),TO_DATE('12-02-2021','MM-DD-YYYY'),'CIRCULAR SAW',7727);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('08-14-2021','MM-DD-YYYY'),TO_DATE('02-14-2022','MM-DD-YYYY'),'TABLE SAW',5242);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('06-21-2021','MM-DD-YYYY'),TO_DATE('12-21-2021','MM-DD-YYYY'),'TABLE DRILL',6422);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('03-04-2021','MM-DD-YYYY'),TO_DATE('09-04-2021','MM-DD-YYYY'),'TABLE DRILL',6247);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('05-26-2021','MM-DD-YYYY'),TO_DATE('11-26-2021','MM-DD-YYYY'),'CIRCULAR SAW',7462);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('05-03-2021','MM-DD-YYYY'),TO_DATE('08-03-2021','MM-DD-YYYY'),'JACK HAMMER',2342);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('02-24-2021','MM-DD-YYYY'),TO_DATE('05-24-2021','MM-DD-YYYY'),'MITRE SAW',6436);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('06-28-2021','MM-DD-YYYY'),TO_DATE('10-28-2021','MM-DD-YYYY'),'HAND SAW',8577);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('01-01-2021','MM-DD-YYYY'),TO_DATE('03-01-2021','MM-DD-YYYY'),'JIGSAW SAW',2632);
INSERT INTO REPAIR_TECHNICIAN (WORKSHOP_ID, LAST_INSPECTION, NEXT_INSPECTION, TOOL_NAME, STAFF_ID)
VALUES(001,TO_DATE('08-18-2021','MM-DD-YYYY'),TO_DATE('11-18-2021','MM-DD-YYYY'),'PHILLIPS SCREWDRIVER',6363);
SELECT * FROM REPAIR_TECHNICIAN;



DESC "MANAGER";
INSERT INTO "MANAGER" VALUES(0001,75000,250000,'2018');
INSERT INTO "MANAGER" VALUES(0028,50000,150000,'2019/Q1');
INSERT INTO "MANAGER" VALUES(0035,50000,150000,'2019/Q2');
INSERT INTO "MANAGER" VALUES(0078,50000,125000,'2019/Q3');
INSERT INTO "MANAGER" VALUES(0091,34000,125000,'2019/Q4');
INSERT INTO "MANAGER" VALUES(0100,34000,125000,'2020/Q1');
INSERT INTO "MANAGER" VALUES(0101,34000,125000,'2020/Q2');
INSERT INTO "MANAGER" VALUES(0120,34000,125000,'2020/Q3');
INSERT INTO "MANAGER" VALUES(0122,34000,125000,'2020/Q4');
INSERT INTO "MANAGER" VALUES(0130,30000,125000,'2021');
SELECT * FROM "MANAGER";

DESC "Order";

INSERT INTO "Order" VALUES(001,00001,1,58,3412,101,40);
INSERT INTO "Order" VALUES(001,00002,1,48,3412,121,30);
INSERT INTO "Order" VALUES(001,00003,3,102,9362,111,70);
INSERT INTO "Order" VALUES(001,00004,1,30,3412,131,15);
INSERT INTO "Order" VALUES(001,00005,3,150,8216,132,115);
INSERT INTO "Order" VALUES(001,00006,1,35,8452,134,20);
INSERT INTO "Order" VALUES(001,00007,2,70,3714,112,50);
INSERT INTO "Order" VALUES(001,00008,2,74,9562,133,50);
INSERT INTO "Order" VALUES(001,00009,4,190,8856,103,135);
INSERT INTO "Order" VALUES(001,00010,1,25,8452,102,10);
SELECT * FROM "Order"


INSERT INTO WORKSHOP (WORKSHOP_ID)
VALUES(001);

SELECT * FROM WORKSHOP;


UPDATE ORDER_COST
SET QUANTITY = 5, TOTAL_COST = 58*5
WHERE ORDER_ID = 1;

UPDATE ORDER_COST
SET QUANTITY = 3, TOTAL_COST = 48*3
WHERE ORDER_ID = 2;

UPDATE ORDER_COST
SET QUANTITY = 2, TOTAL_COST = 30*2
WHERE ORDER_ID = 4;

UPDATE ORDER_COST
SET QUANTITY = 10, TOTAL_COST = 35*10
WHERE ORDER_ID = 6;

UPDATE ORDER_COST
SET QUANTITY = 2, TOTAL_COST = 190*2
WHERE ORDER_ID = 10;

SELECT * FROM ORDER_COST;


UPDATE PART
SET STOCK = 173
WHERE PART_ID = 220;

UPDATE PART
SET STOCK = 350
WHERE PART_ID = 230;

UPDATE PART
SET STOCK = 91
WHERE PART_ID = 250;

UPDATE PART
SET STOCK = 320
WHERE PART_ID = 300;

UPDATE PART
SET STOCK = 300
WHERE PART_ID = 310;

SELECT * FROM PART;


UPDATE PRODUCT
SET PRICE_PER_UNIT = 220
WHERE PRODUCT_ID = 101;

UPDATE PRODUCT
SET PRICE_PER_UNIT = 15
WHERE PRODUCT_ID = 111;

UPDATE PRODUCT
SET PRICE_PER_UNIT = 10
WHERE PRODUCT_ID = 121;

UPDATE PRODUCT
SET PRICE_PER_UNIT = 4
WHERE PRODUCT_ID = 131;

UPDATE PRODUCT
SET PRICE_PER_UNIT = 5
WHERE PRODUCT_ID = 132;


SELECT * FROM PRODUCT;

UPDATE "Session"
SET SESSION_COST = 70
WHERE SESSION_ID = 311010;

UPDATE "Session"
SET SESSION_COST = 70
WHERE SESSION_ID = 141111;

UPDATE "Session"
SET SESSION_COST = 70
WHERE SESSION_ID = 281010;

UPDATE "Session"
SET SESSION_COST = 70
WHERE SESSION_ID = 301010;

UPDATE "Session"
SET SESSION_COST = 75
WHERE SESSION_ID = 31222;

SELECT * FROM "Session";

UPDATE STAFF
SET PHONE_NUMBER = 7551414
WHERE STAFF_ID = 723;

UPDATE STAFF
SET SALARY = 300
WHERE STAFF_ID = 865;

UPDATE STAFF
SET SALARY = 300
WHERE STAFF_ID = 5282;

UPDATE STAFF
SET EMAIL = 'PeterJ@yahoo.com'
WHERE STAFF_ID = 4528;

UPDATE STAFF
SET PHONE_NUMBER = 8886933
WHERE STAFF_ID = 363;

SELECT * FROM STAFF;

UPDATE STAFF_ADDRESS
SET CITY = 'JERUDONG', STREET = 'SIMPANG 611', HOUSE_NUMBER = '13', ZIP_CODE = 'BG3122'
WHERE STAFF_ADDRESS_ID = 723;

UPDATE STAFF_ADDRESS
SET CITY = 'LAMBAK KANAN', ZIP_CODE = 'BU1230'
WHERE STAFF_ADDRESS_ID = 5282;

UPDATE STAFF_ADDRESS
SET DISTRICT = 'BANDAR SERI BEGAWAN'
WHERE DISTRICT = 'BSB';

UPDATE STAFF_ADDRESS
SET DISTRICT = 'TUTONG'
WHERE DISTRICT = 'TTG';

UPDATE STAFF_ADDRESS
SET HOUSE_NUMBER = 86
WHERE STAFF_ADDRESS_ID = 6291;

SELECT * FROM STAFF_ADDRESS;


UPDATE SUPERVISOR
SET ASSIGNED_ROOM = 20
WHERE STAFF_ID = 1916;

UPDATE SUPERVISOR
SET ASSIGNED_ROOM = 21
WHERE STAFF_ID = 455;

UPDATE SUPERVISOR
SET ASSIGNED_ROOM = 30
WHERE STAFF_ID = 9494;

UPDATE SUPERVISOR
SET ASSIGNED_ROOM = 30
WHERE STAFF_ID = 282;

UPDATE SUPERVISOR
SET ASSIGNED_ROOM = 10
WHERE STAFF_ID = 1923;

SELECT * FROM SUPERVISOR;

UPDATE TOOL
SET TOOL_ID = 905
WHERE TOOL_ID = 5;

UPDATE TOOL
SET TOOL_ID = 906
WHERE TOOL_ID = 6;

UPDATE TOOL
SET TOOL_TYPE = 'MACHINERY'
WHERE TOOL_ID = 331;

UPDATE TOOL
SET AVAILABLE = 15
WHERE TOOL_ID = 905;

UPDATE TOOL
SET AVAILABLE = 100
WHERE TOOL_ID = 105;

SELECT * FROM TOOL;



DELETE FROM ORDER_COST
WHERE ORDER_ID = 1;
DELETE FROM ORDER_COST
WHERE ORDER_ID = 2;
DELETE FROM ORDER_COST
WHERE ORDER_ID = 3;
DELETE FROM ORDER_COST
WHERE ORDER_ID = 4;
DELETE FROM ORDER_COST
WHERE ORDER_ID = 5;

SELECT * FROM ORDER_COST;

DELETE FROM PART
WHERE PART_ID = 590;
DELETE FROM PART
WHERE PART_SUPPLIER = 'KAYUBN';
DELETE FROM PART
WHERE PART_ID = 560;

SELECT * FROM PART;

DELETE FROM PRODUCT
WHERE PRODUCT_ID = 111;
DELETE FROM PRODUCT
WHERE ORDER_ID = 9;
DELETE FROM PRODUCT
WHERE ORDER_ID = 6;
DELETE FROM PRODUCT
WHERE ORDER_ID = 5;

SELECT * FROM PRODUCT;

DELETE FROM REPAIR_TECHNICIAN
WHERE TOOL_NAME = 'TABLE DRILL';
DELETE FROM REPAIR_TECHNICIAN
WHERE TOOL_NAME = 'CIRCULAR SAW';
DELETE FROM REPAIR_TECHNICIAN
WHERE TOOL_NAME = 'HAND SAW';

SELECT * FROM REPAIR_TECHNICIAN;


DELETE FROM "Session"
WHERE WORKSPACE_NO = 20;
DELETE FROM "Session"
WHERE SESSION_ID = 31222;

SELECT * FROM "Session";


DELETE FROM STAFF
WHERE STAFF_ID = 723;
DELETE FROM STAFF
WHERE STAFF_ID = 853;
DELETE FROM STAFF
WHERE STAFF_ID = 865;
DELETE FROM STAFF
WHERE STAFF_ID = 975;
DELETE FROM STAFF
WHERE STAFF_ID = 1085;

SELECT * FROM STAFF;

DELETE FROM STAFF_ADDRESS
WHERE STAFF_ADDRESS_ID = 723;
DELETE FROM STAFF_ADDRESS
WHERE STAFF_ADDRESS_ID = 853;
DELETE FROM STAFF_ADDRESS
WHERE STAFF_ADDRESS_ID = 865;
DELETE FROM STAFF_ADDRESS
WHERE STAFF_ADDRESS_ID = 975;
DELETE FROM STAFF_ADDRESS
WHERE STAFF_ADDRESS_ID = 1085;

SELECT * FROM STAFF_ADDRESS;

DELETE FROM SUPERVISOR
WHERE STAFF_ID = 733;
DELETE FROM SUPERVISOR
WHERE STAFF_ID = 1923;
DELETE FROM SUPERVISOR
WHERE STAFF_ID = 911;
DELETE FROM SUPERVISOR
WHERE STAFF_ID = 455;
DELETE FROM SUPERVISOR
WHERE STAFF_ID = 1916;

SELECT * FROM SUPERVISOR;


DELETE FROM TOOL
WHERE TOOL_ID = 330;
DELETE FROM TOOL
WHERE TOOL_ID = 331;
DELETE FROM TOOL
WHERE TOOL_ID = 332;
DELETE FROM TOOL
WHERE TOOL_ID = 333;
DELETE FROM TOOL
WHERE TOOL_ID = 103;

SELECT * FROM TOOL;


DELETE FROM CLEANER WHERE STAFF_ID='788';
DELETE FROM CLEANER WHERE STAFF_ID='887';
DELETE FROM CLEANER WHERE STAFF_ID='1024';
DELETE FROM CLEANER WHERE STAFF_ID='2885';
DELETE FROM CLEANER WHERE STAFF_ID='2936';
SELECT * FROM CLEANER;

UPDATE CLEANER SET OVERTIME_RATE ='0.20' WHERE STAFF_ID='0788';
UPDATE CLEANER SET OVERTIME_RATE ='0.10' WHERE STAFF_ID='0821';
UPDATE CLEANER SET OVERTIME_RATE ='0.15' WHERE STAFF_ID='0887';
UPDATE CLEANER SET EMPLOYEE_OF_THE_MONTH_BONUS ='450' WHERE STAFF_ID='3056';
UPDATE CLEANER SET EMPLOYEE_OF_THE_MONTH_BONUS ='500' WHERE STAFF_ID='2885';


SELECT * FROM STAFF;
DELETE FROM CRAFTMAN WHERE STAFF_ID='1085';
DELETE FROM CRAFTMAN WHERE STAFF_ID='975';
DELETE FROM CRAFTMAN WHERE STAFF_ID='9562';
DELETE FROM CRAFTMAN WHERE STAFF_ID='8856';
DELETE FROM CRAFTMAN WHERE STAFF_ID='8452';
SELECT * FROM CRAFTMAN;


UPDATE CRAFTMAN SET STAFF_ID ='1085' WHERE STAFF_ID='3412'AND ONGOING_PRODUCT='54331';
UPDATE CRAFTMAN SET STAFF_ID ='8392' WHERE STAFF_ID='3412'AND ONGOING_PRODUCT='89976';
UPDATE CRAFTMAN SET STAFF_ID ='0975' WHERE STAFF_ID='8216';
UPDATE CRAFTMAN SET STAFF_ID ='5282' WHERE STAFF_ID='8452'AND ONGOING_PRODUCT='63773';
UPDATE CRAFTMAN SET STAFF_ID ='2874' WHERE STAFF_ID='9362';

SELECT * FROM CUSTOMER;
DELETE FROM CUSTOMER WHERE CUSTOMER_ID='10';
DELETE FROM CUSTOMER WHERE CUSTOMER_ID='13';
DELETE FROM CUSTOMER WHERE CUSTOMER_ID='15';
DELETE FROM CUSTOMER WHERE CUSTOMER_ID='16';
DELETE FROM CUSTOMER WHERE CUSTOMER_ID='18';
SELECT * FROM CUSTOMER;




UPDATE CUSTOMER SET PHONE_NUMBER='2360645' WHERE CUSTOMER_ID='00010';
UPDATE CUSTOMER SET PAYMENT='BANK TRANSFER' WHERE CUSTOMER_ID='00011';
UPDATE CUSTOMER SET DISCOUNTPROMOTION='0.4' WHERE CUSTOMER_ID='00017';
UPDATE CUSTOMER SET PAYMENT='BANK TRANSFER' WHERE CUSTOMER_ID='00013';
UPDATE CUSTOMER SET PHONE_NUMBER='5493210' WHERE CUSTOMER_ID='00015';


DELETE FROM customer_address_id WHERE CUSTOMER_ADDRESS_ID='1001';
DELETE  FROM customer_address_id WHERE CUSTOMER_ADDRESS_ID='1002';
DELETE  FROM customer_address_id WHERE CUSTOMER_ADDRESS_ID='1003';
DELETE  FROM customer_address_id WHERE CUSTOMER_ADDRESS_ID='1004';
DELETE  FROM customer_address_id WHERE CUSTOMER_ADDRESS_ID='1005';
SELECT * FROM customer_address_id;




UPDATE CUSTOMER_ADDRESS_ID SET STREET ='SIMPANG 1' WHERE CUSTOMER_ADDRESS_ID='1001';
UPDATE CUSTOMER_ADDRESS_ID SET HOUSE_NUMBER ='49' WHERE CUSTOMER_ADDRESS_ID='1002';
UPDATE CUSTOMER_ADDRESS_ID SET ZIP_CODE ='KY9936' WHERE CUSTOMER_ADDRESS_ID='1003';
UPDATE CUSTOMER_ADDRESS_ID SET CITY ='LAMBAK KIRI' WHERE CUSTOMER_ADDRESS_ID='1004';
UPDATE CUSTOMER_ADDRESS_ID SET HOUSE_NUMBER ='36' WHERE CUSTOMER_ADDRESS_ID='1005';


DELETE FROM FACILITATOR WHERE STAFF_ID='2874';
DELETE FROM FACILITATOR WHERE STAFF_ID='6291';
DELETE FROM FACILITATOR WHERE STAFF_ID='6788';
DELETE FROM FACILITATOR WHERE STAFF_ID='865';
DELETE FROM FACILITATOR WHERE STAFF_ID='723';
SELECT * FROM FACILITATOR;


UPDATE FACILITATOR SET "DEGREE"='HND' WHERE STAFF_ID='0853';
UPDATE FACILITATOR SET "DEGREE"='HND' WHERE STAFF_ID='0865';
UPDATE FACILITATOR SET "DEGREE"='HND' WHERE STAFF_ID='1235';
UPDATE FACILITATOR SET "DEGREE"='HND' WHERE STAFF_ID='6788';
UPDATE FACILITATOR SET "DEGREE"='DIPLOMA' WHERE STAFF_ID='2874';

DELETE FROM FIRST_AIDER WHERE STAFF_ID='9980';
DELETE FROM FIRST_AIDER WHERE STAFF_ID='9982';
DELETE FROM FIRST_AIDER WHERE STAFF_ID='9987';
DELETE FROM FIRST_AIDER WHERE STAFF_ID='9983';
DELETE FROM FIRST_AIDER WHERE STAFF_ID='9984';
SELECT * FROM FIRST_AIDER;

UPDATE FIRST_AIDER SET LICENSE='EXPIRED' WHERE STAFF_ID='9980';
UPDATE FIRST_AIDER SET LICENSE='EXPIRED' WHERE STAFF_ID='9981';
UPDATE FIRST_AIDER SET LICENSE='EXPIRED' WHERE STAFF_ID='9982';
UPDATE FIRST_AIDER SET LICENSE='VALID' WHERE STAFF_ID='9983';
UPDATE FIRST_AIDER SET TRAINING='IN PROGRESS' WHERE STAFF_ID='9987';

DELETE FROM MANAGER WHERE WORKSHOP_ID='1';
DELETE FROM MANAGER WHERE WORKSHOP_ID='28';
DELETE FROM MANAGER WHERE WORKSHOP_ID='35';
DELETE FROM MANAGER WHERE WORKSHOP_ID='78';
DELETE FROM MANAGER WHERE WORKSHOP_ID='91';
SELECT * FROM MANAGER;

UPDATE MANAGER SET BUDGET='80000' WHERE WORKSHOP_ID='1';
UPDATE MANAGER SET BUDGET='65000' WHERE WORKSHOP_ID='28';
UPDATE MANAGER SET BUDGET='40000' WHERE WORKSHOP_ID='35';
UPDATE MANAGER SET TARGET_REVENUE='180000' WHERE WORKSHOP_ID='78';
UPDATE MANAGER SET TARGET_REVENUE='200000' WHERE WORKSHOP_ID='130';

DELETE FROM "Order" WHERE ORDER_ID='1' ;
DELETE FROM "Order" WHERE ORDER_ID='3' ;
DELETE FROM "Order" WHERE ORDER_ID='9' ;
DELETE FROM "Order" WHERE ORDER_ID='5' ;
DELETE FROM "Order" WHERE ORDER_ID='4' ;
SELECT * FROM "Order";


UPDATE "Order" SET TOTAL_COST='100' WHERE PRODUCT_ID='101';
UPDATE "Order" SET TOTAL_COST='90' WHERE PRODUCT_ID='121';
UPDATE "Order" SET QUANTITY='8' WHERE PRODUCT_ID='131';
UPDATE "Order" SET QUANTITY='3' WHERE PRODUCT_ID='134';
UPDATE "Order" SET TOTAL_COST='105' WHERE PRODUCT_ID='134';

